# Generated by Django 4.2.7 on 2025-12-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='captured_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_reference', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='KeyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[('A', 'A - Length from shoulder'), ('B', 'B - Chest width'), ('C', 'C - Chest width (armholes)'), ('D', 'D - Bottom width'), ('E', 'E - New width'), ('F', 'F - Back width'), ('G', 'G - Back width (armholes)'), ('H', 'H - Neck width'), ('I', 'I - Sleeve length'), ('J', 'J - Sleeve width'), ('K', 'K - Sleeve width above cuff'), ('L', 'L - Sleeve opening'), ('M', 'M - Cuff length'), ('N', 'N - Armhole'), ('O', 'O - Back neck drop'), ('P', 'P - Front neck drop'), ('Q', 'Q - Collar width'), ('R', 'R - Shoulder drop'), ('S', 'S - Waistband length'), ('T', 'T - Forward shoulder seam')], max_length=1)),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keypoints', to='measurements.capturedimage')),
            ],
        ),
        migrations.AddField(
            model_name='capturedimage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='measurements.measurementsession'),
        ),
        migrations.CreateModel(
            name='MeasurementResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='UNKNOWN', max_length=20)),
                ('measured_values', models.JSONField(default=dict)),
                ('standard_values', models.JSONField(default=dict)),
                ('deviations', models.JSONField(default=dict)),
                ('measurement_details', models.JSONField(default=dict)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('operator_id', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_result', to='measurements.measurementsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['passed'], name='measurement_passed_dd10b3_idx'), models.Index(fields=['validation_timestamp'], name='measurement_validat_9ba608_idx')],
            },
        ),
    ]
