# Generated by Django 4.2.7 on 2025-12-21 14:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True, verbose_name='PO Number')),
                ('date', models.DateField()),
                ('brand', models.CharField(choices=[('ZARA', 'ZARA'), ('INDITEX', 'INDITEX'), ('H&M', 'H&M'), ('OTHER', 'Other')], max_length=100)),
                ('origin_country', models.CharField(max_length=100, verbose_name='Origin/Country')),
                ('article_type', models.CharField(choices=[('sweat_shirt', 'Sweat Shirt'), ('hoodie', 'Hoodie'), ('tshirt', 'T-Shirt'), ('pants', 'Pants')], default='sweat_shirt', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandardSizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('6/7', '6/7 Years'), ('7/8', '7/8 Years'), ('8/9', '8/9 Years'), ('9/10', '9/10 Years'), ('10/11', '10/11 Years'), ('12/13', '12/13 Years'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10, unique=True)),
                ('A_length_from_shoulder', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='A - Length from shoulder')),
                ('B_chest_width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='B - Chest width')),
                ('C_chest_width_armholes', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='C - Chest width (12 armholes)')),
                ('D_bottom_width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='D - Bottom width')),
                ('E_new_width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='E - New width')),
                ('F_back_width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='F - Back width')),
                ('G_back_width_armholes', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='G - Back width (12 armholes)')),
                ('H_neck_width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='H - Neck width')),
                ('I_sleeve_length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='I - Sleeve length')),
                ('J_sleeve_width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='J - Sleeve width')),
                ('K_sleeve_width_above_cuff', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='K - Sleeve width above cuff')),
                ('L_sleeve_opening', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='L - Sleeve opening')),
                ('M_cuff_length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='M - Cuff length')),
                ('N_armhole', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='N - Armhole')),
                ('O_back_neck_drop', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='O - Back neck drop')),
                ('P_front_neck_drop', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='P - Front neck drop')),
                ('Q_collar_width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Q - Collar width')),
                ('R_shoulder_drop', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='R - Shoulder drop')),
                ('S_waistband_length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='S - Waistband length')),
                ('T_forward_shoulder_seam', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='T - Forward shoulder seam')),
                ('front_placement_from_cf', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Front placement from CF')),
            ],
            options={
                'verbose_name': 'Standard Size Chart',
                'verbose_name_plural': 'Standard Size Charts',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('6/7', '6/7 Years'), ('7/8', '7/8 Years'), ('8/9', '8/9 Years'), ('9/10', '9/10 Years'), ('10/11', '10/11 Years'), ('12/13', '12/13 Years'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('color', models.CharField(max_length=50)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.purchaseorder')),
            ],
        ),
    ]
